<script setup>
import {computed,onBeforeUnmount,onMounted,reactive,ref} from 'vue'
import {api} from './api'
import LoginPanel from './components/LoginPanel.vue'
import AppSidebar from './components/AppSidebar.vue'
import AppTopbar from './components/AppTopbar.vue'
import {navigationItems} from './config/navigation'
import {panelPresets} from './config/panelPresets'
const appVersion=ref('…')
const active=ref('dashboard'),busy=ref(false),toast=ref(''),preview=ref(''),me=ref(null),selectedDeviceId=ref(''),selectedRetryId=ref('')
const state=reactive({dashboard:{},templates:[],devices:[],schedules:[],sources:[],history:[],retryPolicies:[],users:[],roles:[],permissions:[]})
const allNav=navigationItems
const allowed=p=>me.value?.isAdmin||me.value?.permissions?.includes('*')||me.value?.permissions?.includes(p),nav=computed(()=>allNav.filter(x=>allowed(x[3]))),defaultDevice=computed(()=>state.devices.find(x=>x.isDefault))
const forms=reactive({device:{name:'我的AirPage',deviceUrl:'',isDefault:true},schedule:{name:'工作日行情',templateId:'',deviceId:'',retryPolicyId:'',cron:'30 9 * * 1-5',timeZoneId:'Asia/Shanghai',enabled:true},source:{name:'业务接口',method:'GET',url:'https://api.example.com/status',headersJson:'',body:'',enabled:true},template:{name:'自定义状态面板',type:'custom',description:'',dataSourceId:'',schemaJson:'{}'},retry:{name:'默认重试',maxAttempts:3,initialDelayMs:500,backoffFactor:2,maxDelayMs:5000,retryPreview:true,retryPush:true,isDefault:true},user:{username:'',displayName:'',password:'',isActive:true,isAdmin:false,roleIds:[]},role:{name:'',description:'',permissions:[]},designer:{name:'每日金句',description:'安全JSON绘制模板',code:'{"preset":"quote","title":"每日金句","quote":"保持专注，把复杂的事做简单。","author":"佚名"}'}})
const editing=reactive({schedule:null,template:null,retry:null,user:null,role:null})
async function act(fn,message){busy.value=true;try{await fn();toast.value=message;if(me.value)await load()}catch(e){toast.value=e.message}finally{busy.value=false;setTimeout(()=>toast.value='',4000)}}
async function signIn(credentials){await act(async()=>{me.value=await api.login(credentials);await load()},'登录成功')}
async function signOut(){busy.value=true;try{await api.logout()}catch(e){toast.value=e.message}finally{me.value=null;active.value='dashboard';preview.value='';selectedDeviceId.value='';Object.keys(state).forEach(k=>state[k]=Array.isArray(state[k])?[]:{});busy.value=false;window.history.replaceState({},'',window.location.pathname)}}
async function bootstrap(){try{appVersion.value=(await api.version()).version}catch{}try{me.value=await api.me();await load()}catch{me.value=null}}
async function load(){me.value=await api.me();const calls=[['dashboard',api.dashboard()],['templates',api.templates()],['devices',api.devices()],['schedules',api.schedules()],['sources',api.sources()],['history',api.history()],['retryPolicies',api.retryPolicies()]];if(allowed('menu.users'))calls.push(['users',api.users()],['roles',api.roles()],['permissions',api.permissions()]);const results=await Promise.allSettled(calls.map(x=>x[1]));results.forEach((r,i)=>{if(r.status==='fulfilled')state[calls[i][0]]=r.value});if(!nav.value.some(x=>x[0]===active.value))active.value=nav.value[0]?.[0]||'dashboard';selectedDeviceId.value||=defaultDevice.value?.id||state.devices[0]?.id||'';selectedRetryId.value||=state.retryPolicies.find(x=>x.isDefault)?.id||'';forms.schedule.templateId||=state.templates[0]?.id||'';forms.schedule.deviceId||=selectedDeviceId.value;forms.schedule.retryPolicyId||=selectedRetryId.value}
async function execute(t,push=true){await act(async()=>{const r=await api.execute({templateId:t.id,deviceId:push?(selectedDeviceId.value||null):null,retryPolicyId:selectedRetryId.value||null,push});preview.value=r.previewPath},push?'面板已生成并提交推送':'预览已生成')}
async function addDevice(){await act(async()=>{await api.addDevice(forms.device);forms.device.deviceUrl=''},'设备已安全添加')}
function begin(kind,item){editing[kind]=item.id;Object.assign(forms[kind],item);if(kind==='user')forms.user.password='';if(kind==='role')forms.role.permissions=item.permissions||[]}
async function saveSchedule(){const id=editing.schedule,body={...forms.schedule,retryPolicyId:forms.schedule.retryPolicyId||null};await act(()=>id?api.updateSchedule(id,body):api.addSchedule(body),id?'任务已更新':'任务已创建');editing.schedule=null}
async function saveTemplate(){const id=editing.template,body={...forms.template,dataSourceId:forms.template.dataSourceId||null};await act(()=>id?api.updateTemplate(id,body):api.addTemplate(body),'模板已更新');editing.template=null}
async function previewDraft(form=forms.template){try{JSON.parse(form.schemaJson||'{}')}catch{toast.value='面板代码不是有效JSON';return}busy.value=true;try{const blob=await api.previewTemplate({name:form.name,type:form.type,dataSourceId:form.dataSourceId||null,schemaJson:form.schemaJson});if(preview.value?.startsWith('blob:'))URL.revokeObjectURL(preview.value);preview.value=URL.createObjectURL(blob);toast.value='预览已生成'}catch(e){toast.value=e.message}finally{busy.value=false}}
async function saveRetry(){const id=editing.retry;await act(()=>id?api.updateRetryPolicy(id,forms.retry):api.addRetryPolicy(forms.retry),'重试规则已保存');editing.retry=null}
async function saveUser(){const id=editing.user;await act(()=>id?api.updateUser(id,forms.user):api.addUser(forms.user),'用户已保存');editing.user=null;Object.assign(forms.user,{username:'',displayName:'',password:'',isActive:true,isAdmin:false,roleIds:[]})}
async function saveRole(){const id=editing.role;await act(()=>id?api.updateRole(id,forms.role):api.addRole(forms.role),'角色已保存');editing.role=null;Object.assign(forms.role,{name:'',description:'',permissions:[]})}
async function saveDesigner(){try{JSON.parse(forms.designer.code)}catch{toast.value='面板代码不是有效JSON';return}await act(()=>api.addTemplate({name:forms.designer.name,type:'designer',description:forms.designer.description,dataSourceId:null,schemaJson:forms.designer.code}),'自定义面板已创建');active.value='templates'}
function preset(name){const value=panelPresets[name];forms.designer.name=value[0];forms.designer.code=JSON.stringify(value[1],null,2)}
function attachImage(event){const file=event.target.files?.[0];if(!file||file.size>2*1024*1024){toast.value='图片不能超过2 MiB';return}const reader=new FileReader();reader.onload=()=>{forms.designer.name='图片面板';forms.designer.code=JSON.stringify({title:'图片面板',footer:'上传图片自动适配',elements:[{type:'image',data:reader.result,x:14,y:95,width:500,height:630}]},null,2)};reader.readAsDataURL(file)}
const expire=()=>{me.value=null;toast.value='登录已过期，请重新登录'}
onMounted(()=>{window.addEventListener('airpage:auth-expired',expire);bootstrap()})
onBeforeUnmount(()=>window.removeEventListener('airpage:auth-expired',expire))
</script>
<template>
<LoginPanel v-if="!me" :busy="busy" :version="appVersion" @login="signIn"/>
<div v-else class="shell"><AppSidebar :items="nav" :active="active" :user="me" :default-device="defaultDevice" :version="appVersion" @navigate="active=$event"/>
<main><AppTopbar :title="allNav.find(x=>x[0]===active)?.[1]" subtitle="用户隔离 · 权限控制 · 可靠重试 · 2-bit gray4" :busy="busy" @refresh="load" @logout="signOut"/>
<section v-if="active==='dashboard'"><div class="stats"><article><span>我的设备</span><strong>{{state.dashboard.devices||0}}</strong></article><article><span>可用模板</span><strong>{{state.dashboard.templates||0}}</strong></article><article><span>运行任务</span><strong>{{state.dashboard.schedules||0}}</strong></article><article><span>今日推送</span><strong>{{state.dashboard.pushesToday||0}}</strong></article></div><div class="grid two"><article class="card"><div class="form-grid"><label>推送设备<select v-model="selectedDeviceId"><option v-for="d in state.devices" :value="d.id">{{d.name}}{{d.isDefault?'（默认）':''}}</option></select></label><label>重试规则<select v-model="selectedRetryId"><option value="">单次执行</option><option v-for="r in state.retryPolicies" :value="r.id">{{r.name}}</option></select></label></div><div class="template-row" v-for="t in state.templates"><span class="template-icon">{{t.type==='market'?'↗':t.type==='3xui-monitor'?'⇄':'✦'}}</span><div><b>{{t.name}}</b><small>{{t.description}}</small></div><button @click="execute(t,true)">推送</button><button class="outline" @click="execute(t,false)">预览</button></div></article><article class="card preview"><h2>最近预览</h2><div class="screen"><img v-if="preview" :src="preview"><div v-else>生成面板后在此预览</div></div></article></div></section>
<section v-if="active==='templates'"><div class="grid cards"><article class="card template-card" v-for="t in state.templates"><span class="tag">{{t.isBuiltIn?'内置':'私有'}}</span><div class="big-icon">{{t.type==='3xui-monitor'?'⇄':t.type==='stock-watch'?'股':t.type==='fund-watch'?'基':'✦'}}</div><h2>{{t.name}}</h2><p>{{t.description}}</p><div class="actions"><button @click="execute(t,true)">推送</button><button class="outline" @click="execute(t,false)">预览</button><button class="outline" @click="begin('template',t)">编辑</button></div></article></div><div v-if="editing.template" class="grid two editor-preview"><article class="card form-card"><h2>编辑模板</h2><div class="form-grid"><label>名称<input v-model="forms.template.name"></label><label class="wide">描述<input v-model="forms.template.description"></label><label class="wide" v-if="!state.templates.find(x=>x.id===editing.template)?.isBuiltIn||['stock-watch','fund-watch','designer','daily-quote'].includes(forms.template.type)">模板代码<textarea v-model="forms.template.schemaJson" rows="18"></textarea><small v-if="['stock-watch','fund-watch'].includes(forms.template.type)">格式：{"codes":["600519","000001"]}，最多10个代码</small></label></div><div class="actions"><button @click="saveTemplate">保存</button><button class="outline" @click="previewDraft()">直接预览</button></div></article><article class="card preview"><h2>编辑效果预览</h2><div class="screen"><img v-if="preview" :src="preview"><div v-else>修改代码后点击“直接预览”</div></div></article></div></section>
<section v-if="active==='designer'"><div class="grid two editor-preview"><article class="card form-card"><h2>自定义面板设计器</h2><p class="hint">支持预设、图片自动适配和安全 JSON 绘制 DSL，不执行任意服务器代码。</p><div class="actions"><button class="outline" @click="preset('quote')">金句</button><button class="outline" @click="preset('badge')">工牌</button><button class="outline" @click="preset('boarding')">登机牌</button><button class="outline" @click="preset('layout')">自由绘制</button><label class="file-button">导入图片<input type="file" accept="image/*" @change="attachImage"></label></div><div class="form-grid top-gap"><label>模板名称<input v-model="forms.designer.name"></label><label>描述<input v-model="forms.designer.description"></label><label class="wide">面板代码<textarea v-model="forms.designer.code" rows="22"></textarea></label></div><div class="actions"><button @click="saveDesigner">保存为模板</button><button class="outline" @click="previewDraft({name:forms.designer.name,type:'designer',dataSourceId:null,schemaJson:forms.designer.code})">直接预览</button></div></article><article class="card preview"><h2>实时效果预览</h2><div class="screen"><img v-if="preview" :src="preview"><div v-else>点击“直接预览”查看生成效果</div></div></article></div></section>
<section v-if="active==='sources'"><article class="card form-card"><h2>HTTP JSON 数据源</h2><div class="form-grid"><label>名称<input v-model="forms.source.name"></label><label>方法<select v-model="forms.source.method"><option>GET</option><option>POST</option></select></label><label class="wide">URL<input v-model="forms.source.url"></label><label class="wide">请求头 JSON<textarea v-model="forms.source.headersJson"></textarea></label><label class="wide">请求体<textarea v-model="forms.source.body"></textarea></label></div><button @click="act(()=>api.addSource(forms.source),'数据源已保存')">保存</button></article><article class="card table-card"><table><tr v-for="s in state.sources"><td>{{s.name}}</td><td>{{s.method}}</td><td>{{s.url}}</td><td><button class="outline" @click="act(()=>api.testSource(s.id),'连接正常')">测试</button></td></tr></table></article></section>
<section v-if="active==='schedules'"><article class="card form-card"><h2>{{editing.schedule?'编辑任务':'创建定时任务'}}</h2><div class="form-grid"><label>名称<input v-model="forms.schedule.name"></label><label>时区<input v-model="forms.schedule.timeZoneId"></label><label>模板<select v-model="forms.schedule.templateId"><option v-for="t in state.templates" :value="t.id">{{t.name}}</option></select></label><label>设备<select v-model="forms.schedule.deviceId"><option v-for="d in state.devices" :value="d.id">{{d.name}}</option></select></label><label>重试规则<select v-model="forms.schedule.retryPolicyId"><option value="">单次执行</option><option v-for="r in state.retryPolicies" :value="r.id">{{r.name}}</option></select></label><label>Cron<input v-model="forms.schedule.cron"></label></div><button @click="saveSchedule">保存任务</button></article><article class="card table-card"><table><thead><tr><th>任务</th><th>下次执行</th><th>结果</th><th>操作</th></tr></thead><tbody><tr v-for="s in state.schedules"><td>{{s.name}}<br><code>{{s.cron}}</code></td><td>{{s.nextRunAt?new Date(s.nextRunAt).toLocaleString():'-'}}</td><td>{{s.lastResult||'-'}}</td><td><div class="actions compact"><button @click="act(()=>api.runSchedule(s.id),'测试完成')">测试</button><button class="outline" @click="begin('schedule',s)">编辑</button><button class="outline" @click="act(()=>api.toggleSchedule(s.id),'状态已更新')">启停</button><button class="danger" @click="act(()=>api.deleteSchedule(s.id),'已删除')">删除</button></div></td></tr></tbody></table></article></section>
<section v-if="active==='retries'"><article class="card form-card"><h2>{{editing.retry?'编辑':'新增'}}重试规则</h2><div class="form-grid"><label>名称<input v-model="forms.retry.name"></label><label>最大尝试<input type="number" min="1" max="10" v-model.number="forms.retry.maxAttempts"></label><label>初始延迟(ms)<input type="number" v-model.number="forms.retry.initialDelayMs"></label><label>退避倍数<input type="number" step="0.5" v-model.number="forms.retry.backoffFactor"></label><label>最大延迟(ms)<input type="number" v-model.number="forms.retry.maxDelayMs"></label><label class="check"><input type="checkbox" v-model="forms.retry.retryPreview">生成失败重试</label><label class="check"><input type="checkbox" v-model="forms.retry.retryPush">推送失败重试</label><label class="check"><input type="checkbox" v-model="forms.retry.isDefault">默认规则</label></div><button @click="saveRetry">保存</button></article><div class="grid cards"><article class="card" v-for="r in state.retryPolicies"><h2>{{r.name}}</h2><p>{{r.maxAttempts}}次 · {{r.initialDelayMs}}ms × {{r.backoffFactor}} · 上限{{r.maxDelayMs}}ms</p><button class="outline" @click="begin('retry',r)">编辑</button></article></div></section>
<section v-if="active==='devices'"><article class="card form-card"><h2>添加我的 AirPage</h2><p class="hint">设备链接按用户加密保存，不会回显。</p><div class="form-grid"><label>名称<input v-model="forms.device.name"></label><label class="wide">设备链接<input type="password" v-model="forms.device.deviceUrl"></label><label class="check"><input type="checkbox" v-model="forms.device.isDefault">默认设备</label></div><button @click="addDevice">添加</button></article><div class="grid cards"><article class="card device-card" v-for="d in state.devices"><span v-if="d.isDefault" class="tag">默认</span><h2>{{d.name}}</h2><p>{{d.width}}×{{d.height}} · {{d.mode}}</p><button v-if="!d.isDefault" @click="act(()=>api.setDefault(d.id),'默认设备已更新')">设为默认</button></article></div></section>
<section v-if="active==='history'"><article class="card table-card"><table><thead><tr><th>时间</th><th>状态</th><th>尝试</th><th>耗时</th><th>结果</th><th>预览</th></tr></thead><tbody><tr v-for="h in state.history"><td>{{new Date(h.createdAt).toLocaleString()}}</td><td>{{h.uploadSucceeded?'成功':'未推送'}}</td><td>{{h.attemptCount||1}}</td><td>{{h.durationMs}}ms</td><td>{{h.message}}</td><td><a :href="h.previewPath" target="_blank">查看</a></td></tr></tbody></table></article></section>
<section v-if="active==='users'"><div class="grid two"><article class="card form-card"><h2>{{editing.user?'编辑':'新增'}}用户</h2><div class="form-grid"><label>用户名<input v-model="forms.user.username" :disabled="!!editing.user"></label><label>显示名<input v-model="forms.user.displayName"></label><label>密码<input type="password" v-model="forms.user.password" placeholder="编辑时留空不修改"></label><label class="check"><input type="checkbox" v-model="forms.user.isActive">启用</label><label class="check"><input type="checkbox" v-model="forms.user.isAdmin">管理员</label><label class="wide">角色<select multiple v-model="forms.user.roleIds"><option v-for="r in state.roles" :value="r.id">{{r.name}}</option></select></label></div><button @click="saveUser">保存用户</button></article><article class="card form-card"><h2>{{editing.role?'编辑':'新增'}}角色</h2><label>角色名称<input v-model="forms.role.name"></label><label>描述<input v-model="forms.role.description"></label><div class="permission-grid"><label class="check" v-for="p in state.permissions"><input type="checkbox" :value="p.code" v-model="forms.role.permissions"><span><b>{{p.name}}</b><small>{{p.code}}</small></span></label></div><button @click="saveRole">保存角色</button></article></div><article class="card table-card"><table><tr v-for="u in state.users"><td>{{u.username}}</td><td>{{u.displayName}}</td><td>{{u.isAdmin?'管理员':'普通用户'}}</td><td>{{u.isActive?'启用':'停用'}}</td><td><button class="outline" @click="begin('user',u)">编辑</button></td></tr></table></article><article class="card table-card"><table><tr v-for="r in state.roles"><td>{{r.name}}</td><td>{{r.permissions.map(code=>state.permissions.find(p=>p.code===code)?.name||code).join('、')}}</td><td><button class="outline" @click="begin('role',r)">编辑</button></td></tr></table></article></section>
</main><div class="toast" v-if="toast&&me">{{toast}}</div></div><div class="toast" v-if="toast&&!me">{{toast}}</div>
</template>
